### ISSUE TITLE
Support monorepos without synchronized versions

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/action-publish-release#45]
Currently this action only supports monorepos with synchronized versions. We will soon be using monorepos that don't use synchronized versions, so this will need to be updated to support that.

**Comment by mcmire** [comment]
Just an update on this: Instead of having this action take a second input, we should read the value of `versionSynchronizationStrategy` from some sort of configuration object that is kept in the repo as described here: https://github.com/MetaMask/create-release-branch/blob/88ec7e222c8c8e3fa88534c0ebda331a117911db/docs/setup.md. @rickycodes and I are discussing in Slack whether this configuration object lives in `package.json` or in a separate file entirely, so until that's resolved we can work around it for now by continuing to have a second action input, and then tweak it in a later PR.

**Comment by mcmire** [comment]
Another update: instead of using a version format of `<year>.<month>.<day>-<release number>` for the root package, we should use `<yyyy><mm><dd>.<release number>.0`, so that we don't create a prerelease version.

**Comment by mcmire** [comment]
Here's the relevant part of the Notion doc which describes how this action fits into the larger workflow. This might be helpful to gain more context: https://www.notion.so/Core-Monorepo-Release-Automation-a65b28ab89a14c9d82dcf9fabc3eb1e1#aa00c0fc1e404448884f41c4998602e6
